# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-10 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160527_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='文章描述'),
        ),
    ]
