# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-11 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=10, verbose_name='名称')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('IPaddress', models.GenericIPAddressField(default='1.0.0.1')),
                ('runningTime', models.FloatField(default=0)),
            ],
        ),
    ]
