# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-11 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trex',
            name='IPaddress',
        ),
        migrations.AddField(
            model_name='trex',
            name='address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
